### ISSUE TITLE
Solve DMRIInstall error upon starting SlicerSALT

### ISSUE THREAD

**Issue by bpaniagua** [Kitware/SlicerSALT#16] opened 2017-05-10 14:48 UTC

**Comment by bpaniagua** [comment] 2017-10-05 18:11
Traceback (most recent call last):
File "/work/Projects/slicerSALT/SlicerSALT-0.1.0-c988d2d-linux-amd64/lib/Slicer-4.7/qt-scripted-modules/DMRIInstall.py", line 33, in init
model = slicer.app.extensionsManagerModel()
AttributeError: qSlicerApplication has no attribute named 'extensionsManagerModel'

**Comment by phcerdan** [comment] 2018-08-14 16:47
Cannot reproduce after #40. Closing by now, please reopen if still relevant.

**Closed by phcerdan** 2018-08-14 16:47 UTC
