### ISSUE TITLE
DataImporter.py throws errors on startup

### ISSUE THREAD

**Issue by bpaniagua** [Kitware/SlicerSALT#33] opened 2017-10-05 18:05 UTC
Traceback (most recent call last):
  File "/work/Projects/slicerSALT/SlicerSALT-0.1.0-c988d2d-linux-amd64/lib/Slicer-4.7/qt-scripted-modules/DataImporter.py", line 260, in setup
    self.logic = DataImporterLogic()
  File "/work/Projects/slicerSALT/SlicerSALT-0.1.0-c988d2d-linux-amd64/lib/Slicer-4.7/qt-scripted-modules/DataImporter.py", line 44, in __init__
    self.createSingleDisplaySegmentModelNode()
  File "/work/Projects/slicerSALT/SlicerSALT-0.1.0-c988d2d-linux-amd64/lib/Slicer-4.7/qt-scripted-modules/DataImporter.py", line 51, in createSingleDisplaySegmentModelNode
    if MRMLUtility.isMRMLNodeEmpty(self.singleDisplayedSegmentation, 'vtkMRMLModelNode'):
AttributeError: type object 'MRMLUtility' has no attribute 'isMRMLNodeEmpty'

**Comment by hina-shah** [comment] 2017-10-05 18:07
This is related to the issue #32 . The cause is due to SPHARM-PDM having the same named directory for CommonUtilities which overrides SlicerSALT's directory.

**Comment by bpaniagua** [comment] 2017-10-05 18:08
Thanks @hina-shah 
@laurapascal can you please look into this error?

**Comment by laurapascal** [comment] 2017-12-20 16:58
Resolved in #35

**Closed by laurapascal** 2017-12-20 16:58 UTC
