### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by vicory** [Kitware/SlicerSALT#167] opened 2019-07-10 07:27 UTC
@jcfr  Just to put it on your radar, I've run in to several problems in the last couple of weeks with python 3 compatibility with some of our existing python modules. I can get you a more complete list later but I believe MFSDA/GROUPS/Regression were having problems related to string vs byte encoding and SVA is throwing an error because ListType is not defined in python 3.

**Comment by iPsych** [comment] 2019-07-11 03:42
@vicory I am experiencing similar issues with MacOS + Python3 in Latest versions (SlicerSALT-1.1.0-2019-07-05-macosx-amd64, SlicerSALT-1.1.0-2019-06-19-macosx-amd64.
I guess it's due to filesystem structure of OS. 
In Linux, str - byte problem seems not happen, but in Mac OS, all the import, SPHARM steps show error with Python3.
I think it's migration issue.

**Comment by jcfr** [comment] 2019-07-11 03:46
@iPsych Thanks for the update. As soon as the problem is addressed (most likely tomorrow), we will close this issue.

**Comment by vicory** [comment] 2019-08-05 19:29
@sjh26 I tried to run several modules, here are the problems I've identified so far. Let me know if you need some data to test with or a quick primer on how to run the modules.

### SPHARM-PDM:

Error:
`  File "/work/SALT/build_20190805/Slicer-build/_CPack_Packages/linux-amd64/TGZ/SlicerSALT-1.1.0-2019-08-05-linux-amd64/bin/../lib/SlicerSALT-4.11/qt-scripted-modules/ShapeAnalysisModule.py", line 386, in onInputDirectoryChanged
    if file.endswith(ext):
TypeError: endswith first arg must be bytes or a tuple of bytes, not str
`

Location: 
https://github.com/slicersalt/SPHARM-PDM/blob/slicersalt-2018-11-29-4baa99c10/Modules/Scripted/ShapeAnalysisModule/ShapeAnalysisModule.py#L386

### Shape Variation Analyzer:

Error:
`  File "/work/SALT/build_20190805/Slicer-build/_CPack_Packages/linux-amd64/TGZ/SlicerSALT-1.1.0-2019-08-05-linux-amd64/bin/../lib/SlicerSALT-4.11/qt-scripted-modules/ShapeVariationAnalyzer.py", line 622, in onSelectPreviewGroups
    condition2 = self.logic.creationDictVTKFiles(self.dictVTKFiles)
  File "/work/SALT/build_20190805/Slicer-build/_CPack_Packages/linux-amd64/TGZ/SlicerSALT-1.1.0-2019-08-05-linux-amd64/bin/../lib/SlicerSALT-4.11/qt-scripted-modules/ShapeVariationAnalyzer.py", line 1838, in creationDictVTKFiles
    if type(value) is ListType:
NameError: name 'ListType' is not defined
`

Location:
https://github.com/slicersalt/ShapeVariationAnalyzer/blob/slicersalt-2019-04-24-8340af24e/ShapeVariationAnalyzer/ShapeVariationAnalyzer.py#L1838

### MFSDA:

Error:
`Traceback (most recent call last):
  File "/work/SALT/build_20190805/Slicer-build/_CPack_Packages/linux-amd64/TGZ/SlicerSALT-1.1.0-2019-08-05-linux-amd64/bin/../lib/SlicerSALT-4.11/qt-scripted-modules/MFSDA.py", line 127, in onShapeState
    writer.writerow(Data)
TypeError: a bytes-like object is required, not 'str'
`

Location:
https://github.com/slicersalt/MFSDA_Python/blob/slicersalt-2019-02-13-0a67df1d8/MFSDA/MFSDA.py#L127

### Regression:

Error:
`Traceback (most recent call last):
  File "/work/SALT/build_20190805/Slicer-build/_CPack_Packages/linux-amd64/TGZ/SlicerSALT-1.1.0-2019-08-05-linux-amd64/bin/../lib/SlicerSALT-4.11/qt-scripted-modules/RegressionComputation.py", line 379, in onApplyButton
    self.Logic.runShape4D()
  File "/work/SALT/build_20190805/Slicer-build/_CPack_Packages/linux-amd64/TGZ/SlicerSALT-1.1.0-2019-08-05-linux-amd64/bin/../lib/SlicerSALT-4.11/qt-scripted-modules/RegressionComputation.py", line 407, in runShape4D
    XMLdriverfilepath = self.writeXMLdriverFile()
  File "/work/SALT/build_20190805/Slicer-build/_CPack_Packages/linux-amd64/TGZ/SlicerSALT-1.1.0-2019-08-05-linux-amd64/bin/../lib/SlicerSALT-4.11/qt-scripted-modules/RegressionComputation.py", line 445, in writeXMLdriverFile
    outputDir = self.interface.outputDirectory.directory.encode('utf-8') + "/"
TypeError: can't concat str to bytes
`

Location:
https://github.com/KitwareMedical/ShapeRegressionExtension/blob/slicersalt-2019-04-20-45cc2d4/RegressionComputation/RegressionComputation.py#L445

---

Error:
`Traceback (most recent call last):
  File "/work/SALT/build_20190805/Slicer-build/_CPack_Packages/linux-amd64/TGZ/SlicerSALT-1.1.0-2019-08-05-linux-amd64/bin/../lib/SlicerSALT-4.11/qt-scripted-modules/RegressionComputation.py", line 269, in onInputShapesDirectoryChanged
    if not (curFile.endswith(".vtk")):
TypeError: endswith first arg must be bytes or a tuple of bytes, not str
`

Location:
https://github.com/KitwareMedical/ShapeRegressionExtension/blob/slicersalt-2019-04-20-45cc2d4/RegressionComputation/RegressionComputation.py#L269

**Comment by jcfr** [comment] 2019-08-05 20:59
I suggest we update the modules to only support python3. 

## SPHARM-PDM

Change 

```
inputDirectory = self.GroupProjectInputDirectory.directory.encode('utf-8')
```
to

```
inputDirectory = self.GroupProjectInputDirectory.directory
```

See https://github.com/slicersalt/SPHARM-PDM/blob/slicersalt-2018-11-29-4baa99c10/Modules/Scripted/ShapeAnalysisModule/ShapeAnalysisModule.py#L374

## Shape Variation Analyzer

Change 
```
if type(value) is ListType:
```

to 

```
if isinstance(value, list):
```

## MFSDA

Writing of the CSV file should be changed using this approach. See https://docs.python.org/3/library/csv.html#csv.writer

## Regression

> error 1

I think `encode('utf-8')` should be removed.

> error 2

Same comment.

**Comment by jcfr** [comment] 2019-08-05 21:00
@sjh26 If you don't have the bandwidth to tackle this, I can work on these issues tomorrow morning.  Let me know.

**Comment by sjh26** [comment] 2019-08-05 21:03
Since I have gotten tangled up in getting the Fortran Windows build working again, it would be great if you could take a look at this.

**Comment by bpaniagua** [comment] 2019-08-06 17:02
New error using SPHARM in 1.0
Widget: Running ShapeAnalysisModule
-- Scheduled : ShapeAnalysisModule
2 case(s) found
-- Running : ShapeAnalysisModule
Traceback (most recent call last):
  File "/Users/bpaniagua/Desktop/SlicerSALT.app/Contents/lib/SlicerSALT-4.9/qt-scripted-modules/ShapeAnalysisModule.py", line 626, in onApplyButton
    self.Logic.ShapeAnalysisCases()
  File "/Users/bpaniagua/Desktop/SlicerSALT.app/Contents/lib/SlicerSALT-4.9/qt-scripted-modules/ShapeAnalysisModule.py", line 1194, in ShapeAnalysisCases
    self.startPipeline(0)
  File "/Users/bpaniagua/Desktop/SlicerSALT.app/Contents/lib/SlicerSALT-4.9/qt-scripted-modules/CommonUtilities/LogicMixin.py", line 31, in startPipeline
    self.pipeline[id].setup()
  File "/Users/bpaniagua/Desktop/SlicerSALT.app/Contents/lib/SlicerSALT-4.9/qt-scripted-modules/ShapeAnalysisModule.py", line 1383, in setup
    labelmap_input_node = MRMLUtility.loadMRMLNode(self.inputRootname, inputDirectory, self.CaseInput, 'LabelMap')
  File "/Users/bpaniagua/Desktop/SlicerSALT.app/Contents/lib/SlicerSALT-4.9/qt-scripted-modules/CommonUtilities/utility.py", line 16, in loadMRMLNode
    node = slicer.util.getNode(node_name)
  File "/Users/bpaniagua/Desktop/SlicerSALT.app/Contents/bin/Python/slicer/util.py", line 670, in getNode
    raise MRMLNodeNotFoundException("could not find nodes in the scene by name or id '%s'" % (pattern if (type(pattern) == str) else ""))
slicer.util.MRMLNodeNotFoundException: could not find nodes in the scene by name or id 'cilinder_seg'

**Comment by bpaniagua** [comment] 2019-08-07 14:35
Hi @vovythevov 

SlicerSALT modules are all deployed as extensions that automatically get downloaded and packaged with SALT during the build process.

I believe these issues can be also tested one by one in the latest Slicernightly, by installing each one of the modules as extensions.

You will have to do PRs to each repo independently.

@jcfr @vicory are we already replicating code individually for each module into our own module repos?

Thanks,
Bea

**Comment by vicory** [comment] 2019-08-07 14:38
We have forks of all of the repos that we are packaging from. The links in my post are to those repos, we can worry about migrating changes upstream later. 

I recommend testing from a SALT build rather than installing via Slicer because I believe the Slicer extensions are pulled from the upstream repos.

**Comment by bpaniagua** [comment] 2019-08-07 14:40
Sounds good. @vovythevov please update the issue with each repo fixed when you get to this.

**Comment by sjh26** [comment] 2019-08-08 20:16
@vicory are you working currently on any of these?  I am going to try to knock them out today.

**Comment by vicory** [comment] 2019-08-08 20:18
No from me right now, I finished SPHARM but the others are still pending.

**Comment by sjh26** [comment] 2019-08-09 04:29
PR up for shape regression: https://github.com/KitwareMedical/ShapeRegressionExtension/pull/23

**Comment by sjh26** [comment] 2019-08-09 06:42
PR for Shape Analyzer:

https://github.com/slicersalt/ShapeVariationAnalyzer/pull/1

**Comment by sjh26** [comment] 2019-08-09 16:29
MFSDA PR

https://github.com/slicersalt/MFSDA_Python/pull/1

**Closed** 2019-08-20 14:05 UTC
Labels: bug
